export enum EXCEL_MODULE_NAMES {
  COMPANY_MASTER = "Company Master",
  PROJECT_MASTER = "Project Master",
  WING_MASTER = "Wing Master",
  FLAT_MASTER = "Flat Master",
  CUSTOMER_MASTER = "Customer Master",
  BOOKING_MASTER = "Booking Master",
  CANCELLATION_MASTER = "Cancellation Master",
}

// Excel templates for each module
export const EXCEL_TEMPLATES = {
  companies: [
    "Company Name",
    "CIN",
    "PAN",
    "GSTIN",
    "Address",
    "Contact Person",
    "Contact Number",
    "Email ID",
  ],
  projects: [
    "Project Name",
    "Company Name",
    "Location",
    "Start Date",
    "End Date",
    "Total Carpet Area (Sq.M)",
    "Estimated Land Cost",
    "Estimated Construction Cost",
  ],
  wings: ["Wing Name", "Project Name", "Company Name", "Total Floors"],
  flats: [
    "Flat Number",
    "Wing Name",
    "Company Name",
    "Carpet Area (Sq.M)",
    "Agreement Value",
    "Status (Available/Booked/Sold)",
  ],
  customers: [
    "Customer Name",
    "PAN",
    "Mobile Number",
    "Email",
    "Address",
    "Pin Code",
    "Aadhar Number",
    "Flat Number",
  ],
  bookings: [
    "Flat Number",
    "Customer Name",
    "Agreement Value",
    "Booking Date",
    "Amount Received",
    "Payment Mode",
    "Reference No",
    "Bank Name",
  ],
  cancellations: [
    "Flat Number",
    "Customer Name",
    "Cancellation Date",
    "Refund Amount",
    "Cancellation Reason",
  ],
};
